# Generated by Django 4.1.2 on 2022-11-09 13:53

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("cafe", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cafe",
            old_name="business_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="managedcafe",
            old_name="representative",
            new_name="owner",
        ),
        migrations.RemoveField(
            model_name="cafe",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="managedcafe",
            name="display_name",
        ),
        migrations.AlterField(
            model_name="cafe",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, unique=True
            ),
        ),
    ]
