# Generated by Django 4.1.2 on 2022-11-29 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cafe", "0003_cafe_address_cafe_location_managedcafe_introduction_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cafemenu",
            options={"verbose_name": "cafe_menu", "verbose_name_plural": "cafe_menu"},
        ),
        migrations.AddField(
            model_name="cafemenu",
            name="category",
            field=models.CharField(default="Uncategorized", max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cafemenu",
            name="is_main",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="managedcafe",
            name="liked_users",
            field=models.ManyToManyField(
                related_name="liked_cafes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="cafeimage",
            name="cafe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="cafe.managedcafe",
            ),
        ),
        migrations.AlterField(
            model_name="cafemenu",
            name="cafe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menus",
                to="cafe.managedcafe",
            ),
        ),
        migrations.CreateModel(
            name="CafeReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "One"),
                            (2, "Two"),
                            (3, "Three"),
                            (4, "Four"),
                            (5, "Five"),
                        ],
                        default=5,
                    ),
                ),
                (
                    "strength",
                    models.CharField(
                        choices=[
                            ("Taste", "Taste"),
                            ("Service", "Service"),
                            ("Mood", "Mood"),
                        ],
                        default="Taste",
                        max_length=16,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cafe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="cafe.managedcafe",
                    ),
                ),
            ],
            options={
                "verbose_name": "cafe_review",
                "verbose_name_plural": "cafe_reviews",
            },
        ),
        migrations.AddConstraint(
            model_name="cafereview",
            constraint=models.UniqueConstraint(
                fields=("cafe", "author"), name="unique_review_cafe_author"
            ),
        ),
    ]
