# Generated by Django 4.1.2 on 2022-12-06 17:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("cafe", "0004_alter_cafemenu_options_cafemenu_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cafereview",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
