import { motion } from "framer-motion";
import { NextPage } from "next";
import { AppProps } from "next/app";
import Head from "next/head";
import { ReactElement, ReactNode } from "react";
import "styles/globals.css";

export type NextPageWithLayout<P = {}, IP = P> = NextPage<P, IP> & {
  getLayout?: (page: ReactElement) => ReactNode;
};

type AppPropsWithLayout = AppProps & {
  Component: NextPageWithLayout;
};

function App({ Component, pageProps, router }: AppPropsWithLayout) {
  const getLayout = Component.getLayout ?? ((page) => page);
  const isAdminPage = router.pathname.startsWith("/admin");

  return (
    <>
      <Head>
        <title>{isAdminPage ? "Cago Admin" : "Cago"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      {getLayout(
        <motion.div key={router.route} initial={{ opacity: 0 }} animate={{ opacity: 1 }}>
          <Component {...pageProps} />
        </motion.div>
      )}
    </>
  );
}

export default App;
